storage:
  build: .
  volumes:
    - /data
    - /var/lib/docker/registry
redis:
  image: redis
  command: "redis-server /data/redis.conf"
  volumes_from:
    - storage
  ports:
    - "6379:6379"
registry:
  restart: always
  image: registry:2
  links:
    - redis:redis
  volumes_from:
    - storage
  environment:
    DOCKER_REGISTRY_CONFIG: "/data/registry.yml"
    SETTINGS_FLAVOR: "local"
    SEARCH_BACKEND: sqlalchemy
    CACHE_REDIS_HOST: redis
    CACHE_REDIS_PORT: 6379 
    CACHE_LRU_REDIS_HOST: redis
    CACHE_LRU_REDIS_PORT: 6379
    REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/docker/registry
  ports:
    - "5000:5000"
frontend:
  image: konradkleine/docker-registry-frontend
  links:
    - registry:registry
  ports:
    - "8081:80"
  environment:
    ENV_DOCKER_REGISTRY_HOST: registry
    ENV_DOCKER_REGISTRY_PORT: 5000
