postgres:
  image: paintedfox/postgresql
  environment:
    - USER=gitlab
    - PASS=password
    - DB=gitlab_local
  volumes:
    - /srv/docker/gitlab/postgresql:/var/lib/postgresql
redis:
  image: redis
  command: "redis-server /data/redis.conf"
  volumes_from:
    - storage
  ports:
    - "6379:6379"
gitlab:
  image: gitlab/gitlab-ce:latest
  links:
    - redis:redis
    - postgresql:postgresql
  ports:
    - "10080:80"
    - "10022:22"
  environment:
    - SMTP_ENABLED=false
    - SMTP_DOMAIN=www.example.com
    - SMTP_HOST=smtp.gmail.com
    - SMTP_PORT=587
    - SMTP_USER=mailer@example.com
    - SMTP_PASS=password
    - SMTP_STARTTLS=true
    - SMTP_AUTHENTICATION=login
    - GITLAB_HOST=localhost
    - GITLAB_PORT=10080
    - GITLAB_SSH_PORT=10022
    - GITLAB_EMAIL=admin@example.com
    - GITLAB_EMAIL_REPLY_TO=noreply@example.com
    - GITLAB_BACKUPS=daily
    - GITLAB_BACKUP_TIME=01:00
  volumes:
    - /srv/docker/gitlab/gitlab:/home/git/data
