backend:
  #image: "codeboxsystems/codeboxsystems-backend"
  build: ../../codeboxsystems-backend
  ports:
    - "5000:5000"
frontend:
  #image: "codeboxsystems/codeboxsystems-site"
  build: ../../codeboxsystems-site
  links:
    - backend
  ports:
    - "443:443"
solidisdocs:
  build: ../../solidis-docs
  ports:
    - "3000:80"
liquidisdocs:
  build: ../../liquidis-docs
  ports:
    - "3001:80"
webserver:
  build: .
  links:
    - solidisdocs
    - liquidisdocs
  ports:
    - "80:80"
